import os
import numpy as np
import read_parameters
import ITS

def enhanced_sampling(enhanced_sampling_method, if_initial,\
                      simulation_temperature, simulation_maxsteps, time_step,\
                      potential_energy, current_md_step, md_force,\
                      parameter_file='MoREST.in'):
    '''
    This API function is called to excute enhanced sampling by MD/MC module.
    --------
    INPUT:
        enhanced_sampling_method: Specify the method will be used, e.g., ITS, REMD...
        if_initial:               Specify whether this API is called for the first time.
        simulation_temperature:   The temperature used in MD/MC module. Unit: K.
        simulation_maxsteps:      The simulation length, which is specified in number of steps, in MD/MC module.
        time_step:                The time step in MD/MC module. Unit: ps.
        potential_energy:         The potential energy of current configuration from MD/MC module.
        current_md_step:          This number is used to check whether trial MD is finished.
        md_force:                 The force vector of current configuration from MD/MC module.
        log_morest:               The path and name of the log file for MoREST.
        parameter_file:           The path and name of the parameter file.
    OUTPUT:
        its_bias_force:           The bias force vector generated by ITS and returned to MD/MC module. 
        current_md_step:          The current MD step is returned to identify the number of opt and sampling steps in ITS
    '''
    
    log_morest = open('MoREST.log','a')
    
    if enhanced_sampling_method in ['ITS','its']:
        if if_initial:
            if os.path.isfile('MoREST_ITS_pk.npy'):
                os.remove('MoREST_ITS_pk.npy')
            if os.path.isfile('MoREST_ITS_nk.npy'):
                os.remove('MoREST_ITS_nk.npy')
            if os.path.isfile('MoREST_ITS_potential_energy.list'):
                os.remove('MoREST_ITS_potential_energy.list')
            #if os.path.isfile('MoREST.log'):
            log_morest.close()
            log_morest = open('MoREST.log','w')
            
            log_morest.write('Start to initialize integrated tempering sampling method.\n\n')
            its_parameters = read_parameters.read_parameters(log_morest,parameter_file).get_its_parameters()
            #print(its_parameters)
            its_para = np.load('MoREST_ITS_parameters.npy',allow_pickle=True).item()
            for key in its_para:
                log_morest.write(key+':    '+str(its_para[key])+'\n')
            log_morest.write('\n')
            
            bias_force, current_md_step = ITS.its().its_optimization(simulation_temperature,\
                                                             potential_energy, current_md_step,\
                                                             md_force, log_morest)
            return bias_force, current_md_step
        else:
            if ITS.its().its_if_converge():
                bias_force = ITS.its().its_sampling(simulation_temperature,\
                                                    potential_energy, current_md_step, md_force) 
                return bias_force, current_md_step
            else:
                bias_force, current_md_step = ITS.its().its_optimization(simulation_temperature,\
                                                           potential_energy, current_md_step,\
                                                           md_force, log_morest)
                return bias_force, current_md_step
    else:
        log_morest.write('No enhanced sampling method was matched.\n')
        log_morest.close()
        return np.array([0])
    
