import numpy as np
import read_parameters
import its

def enhanced_sampling(enhanced_sampling_method, if_initial,\
                      simulation_temperature, simulation_maxsteps,\
                      time_step, potential_energy, md_force,\
                      parameter_file='MoREST.parameter'):
    '''
    This API function is called to excute enhanced sampling by MD/MC module.
    --------
    INPUT:
        parameter_file:           The path and name of the parameter file.
        enhanced_sampling_method: Specify the method will be used, e.g., ITS, REMD...
        if_initial:               Specify whether this API is called for the first time.
        simulation_temperature:   The temperature used in MD/MC module. Unit: K.
        simulation_maxsteps:      The simulation length, which is specified in number of steps, in MD/MC module.
        time_step:                The time step in MD/MC module. Unit: ps.
        potential_energy:         The potential energy of current configuration from MD/MC module.
        md_force:                 The force vector of current configuration from MD/MC module.
    OUTPUT:
        its_bias_force:           The bias force vector generated by ITS and returned to MD/MC module. 
    '''
    
    global log_morest
    
    if enhanced_sampling_method == 'ITS' or enhanced_sampling_method == 'its':
        if if_initial:
            # from more import read_parameters
            its_parameters = read_parameters(parameter_file).its_parameters
            print(its_parameters)
            # from its import its_initialization
            its.its_initialization()
            # from its import its_optimization. return bias_force, {p_k}, {n_k}
            bias_force, p_k, n_k = its.its_optimization()
            return bias_force
        else:
            # from its import its_if_converge
            if its.its_if_converge():
                # from its import import its_sampling
                bias_force = its.its_sampling() 
                return bias_force
            else:
                # from its import its_optimization
                bias_force, p_k, n_k = its.its_optmization()
                return bias_force
    else:
        log_morest.write('No enhanced sampling method was matched.\n')
        return np.array([0])
    
enhanced_sampling('ITS', True, 798, 10000, 0.0001, 4000,\
                  np.array([[1.,2.,3.],[1.,3.,2.],[3.,1.,2.],[3.,2.,1.]]))