import os, sys
import numpy as np
from read_parameters import read_parameters
from enhanced_sampling_ITS import its
from wall_potential_Plane_wall import plane_opaque_wall, plane_translucent_wall


class morest:
    '''
    The Molecular Reaction Simulation Toolkits module.
    '''

    def __init__(self, __parameter_file='MoREST.in'):
        self.__log_morest = open('MoREST.log','w')
        MoREST_parameters = read_parameters(log_morest=self.__log_morest, parameter_file=__parameter_file)

        self.enhanced_sampling_parameters = MoREST_parameters.get_enhanced_sampling_parameters()
        #for key in self.enhanced_sampling_parameters:
        #    print(key+' : '+str(self.enhanced_sampling_parameters[key]))
        if self.enhanced_sampling_parameters['enhanced_sampling']:
            self.its_parameters = MoREST_parameters.get_its_parameters()
        #    for key in self.its_parameters:
        #        print(key+' : '+str(self.its_parameters[key]))

        self.wall_potential_parameters = MoREST_parameters.get_wall_potential_parameters()
        #for key in self.wall_potential_parameters:
        #    print(key+' : '+str(self.wall_potential_parameters[key]))
        if self.wall_potential_parameters['wall_potential']:
            self.plane_wall_parameters = MoREST_parameters.get_plane_wall_parameters()
        #    for key in self.plane_wall_parameters:
        #        print(key+' : '+str(self.plane_wall_parameters[key]))

    
    
    def enhanced_sampling(self, if_initial, simulation_temperature, simulation_maxsteps, \
                   time_step, potential_energy, current_md_step, md_force):
        '''
        This API function is called to excute enhanced sampling by MD/MC module.
        --------
        INPUT:
            enhanced_sampling_method: Specify the method will be used, e.g., ITS, REMD...
            if_initial:               Specify whether this API is called for the first time.
            simulation_temperature:   The temperature used in MD/MC module. Unit: K.
            simulation_maxsteps:      The simulation length, which is specified in number of steps, in MD/MC module.
            time_step:                The time step in MD/MC module. Unit: ps.
            potential_energy:         The potential energy of current configuration from MD/MC module.
            current_md_step:          This number is used to check whether trial MD is finished.
            md_force:                 The force vector of current configuration from MD/MC module.
        OUTPUT:
            its_bias_force:           The bias force vector generated by ITS and returned to MD/MC module. 
            #current_md_step:          The current MD step is returned to identify the number of opt and sampling steps in ITS
        '''

        if self.enhanced_sampling_parameters['Enhanced_sampling_method'] in ['ITS','its']:
            if if_initial or ( if_initial == 1 ):
                if os.path.isfile('MoREST_ITS_pk.npy'):
                    os.remove('MoREST_ITS_pk.npy')
                if os.path.isfile('MoREST_ITS_nk.npy'):
                    os.remove('MoREST_ITS_nk.npy')
                if os.path.isfile('MoREST_ITS_potential_energy.list'):
                    os.remove('MoREST_ITS_potential_energy.list')

                self.__log_morest.write('Start to initialize integrated tempering sampling method.\n\n')
                for key in self.its_parameters:
                    self.__log_morest.write(key+' : '+str(self.its_parameters[key])+'\n')
                self.__log_morest.write('\n')

                bias_force = its().its_optimization(simulation_temperature,\
                                        potential_energy, current_md_step,\
                                        md_force, self.__log_morest)
                return bias_force
            elif ( not if_initial ) or ( if_initial == 0 ):
                if its().its_if_converge():
                    bias_force = its().its_sampling(simulation_temperature, potential_energy, md_force) 
                    return bias_force
                else:
                    bias_force = its().its_optimization(simulation_temperature, potential_energy, \
                                            current_md_step, md_force, self.__log_morest)
                    return bias_force
        else:
            self.__log_morest.write('No enhanced sampling method was matched.\n')
            self.__log_morest.close()
            return np.array([0])

        
        
    def wall_potential(self, general_coordinate):
        '''
        wall_potential will read the positions of atoms and then add forces of the potential on the atoms.
        INPUT:
        general_coordinate:       The positions vector of atoms in the system.
        OUTPUT:
        wall_force: the forces of the wall potential on the atoms
        '''

        if not self.wall_potential_parameters['collective_variable']:
            if self.wall_potential_parameters['wall_type'] in ['Plane_opaque_wall', 'plane_opaque_wall']:
                self.__log_morest.write('\n')
                self.__log_morest.write('The defination of the plane opaque wall: Point in plane, Normal vector\n')
                self.__log_morest.write(str(self.plane_wall_parameters['plane_wall_point']) + \
                                   ' '+str(self.plane_wall_parameters['plane_wall_normal_vector']))
                self.__log_morest.write('\n')
                self.__log_morest.write('Plane_wall_scaling : '+str(self.plane_wall_parameters['Plane_wall_scaling'])+'\n')
                self.__log_morest.write('Plane_wall_scope : '+str(self.plane_wall_parameters['Plane_wall_scope'])+'\n')
                self.__log_morest.write('The plane opaque wall potential and force on atoms: XYZ coordinate, Potential, Forces\n')
                wall_force = []
                for i_coordinate in general_coordinate:
                    i_wall_force, i_wall_potential = plane_opaque_wall().get_opaque_wall_force_potential(i_coordinate)
                    wall_force.append(i_wall_force)
                    self.__log_morest.write(str(i_coordinate)+' '+str(i_wall_potential)+' '+str(i_wall_force))
                    self.__log_morest.write('\n')
                self.__log_morest.write('\n')
                return np.array(wall_force)

            if wall_potential_parameters['wall_type'] in ['Plane_translucent_wall', 'plane_translucent_wall']:
                plane_wall_parameters = np.load('MoREST_plane_wall_parameters.npy',allow_pickle=True).item()
                self.__log_morest.write('\n')
                self.__log_morest.write('The defination of the plane translucent wall: Point in plane, Normal vector\n')
                self.__log_morest.write(str(self.plane_wall_parameters['plane_wall_point']) + \
                                   ' ' + str(self.plane_wall_parameters['plane_wall_normal_vector']))
                self.__log_morest.write('\n')
                self.__log_morest.write('Plane_wall_scaling : '+str(self.plane_wall_parameters['Plane_wall_scaling'])+'\n')
                self.__log_morest.write('Plane_wall_scope : '+str(self.plane_wall_parameters['Plane_wall_scope'])+'\n')
                self.__log_morest.write('The plane translucent wall potential and force on atoms: XYZ coordinate, Potential, Forces\n')
                wall_force = []
                for i_coordinate in general_coordinate:
                    i_wall_force, i_wall_potential = plane_translucent_wall().get_translucent_wall_force_potential(i_coordinate)
                    wall_force.append(i_wall_force)
                    self.__log_morest.write(str(i_coordinate)+' '+str(i_wall_potential)+' '+str(i_wall_force))
                    self.__log_morest.write('\n')
                self.__log_morest.write('\n')
                return np.array(wall_force)

            else:
                self.__log_morest.write('No wall type was matched.\n')
                self.__log_morest.close()
                return np.array([0])

        else:
            general_coordinate = CV_to_xyz(general_coordinate) # TODO conversion function is not exist.

